### PR TITLE
add CdtrAcct in the xml tree

### PR DESCRIPTION
**Pull request by JonatasViscaino**
Hi Sebastien,

I check your code and I realized that 1 element in the tree is missing, the CdtrAcct.

I added in the code. Please check and let me know if is ok.

Cheers,
Jonatas Rodriguez

### CODE REVIEW

**Comment by sebastienrousseau** [comment]
@JonatasViscaino Thank you for doing this, would you be able to fix the minor unit test and lint issues? Thanks in advance

**Review by JonatasViscaino — COMMENTED** [review]
Hi Sebastien, I removed the spaces.

**Comment by sebastienrousseau** [comment]
@JonatasViscaino still having an issue on the unit test which prevents the build to continue. Can you have a look at it?

**Comment by JonatasViscaino** [comment]
Hi Sebastien, before were you receiving a xml "is valid" response with the previous structure? I checked and there is other mistakes in the structure of the XML v3 that is preventing to pass the test and I would need to change a few of the fields before submitting, this would as well maybe change the structure of the CSV. Another question I have here is why you are passing a xml file in the program as the program itself would need to generate the xml? Why not just pass a xml_file_name and pass in the generate_updated_xml_file_path and return the file name as below: 
def generate_updated_xml_file_path(
    xml_file_name
):
    
    new_file_name = xml_file_name + ".xml"
    return new_file_name
    
    Please let me know your thoughts on this.

**Comment by sebastienrousseau** [comment]
@JonatasViscaino yes I used to receive XML is valid and was also testing this separately using this website to quickly check that my implementation is correct.

<https://www.mobilefish.com/services/sepa_xml_validation/sepa_xml_validation.php>

Happy for you make any changes where you see errors that I made. Again I do believe I need to extend the XSD validation to be more explicit, details and also extend it to validate the CSV construction.

Regarding your last question, I hear you originally I needed something quick and "dirty". There are additional improvements and optimisation I need to bring. On my own at the moment on this one so happy to get any help I can have to make this product much better, practical and super efficient for the community as there is a real gap in this field.

**Comment by sebastienrousseau** [comment]
@JonatasViscaino Let me know if you are still having issues with the new version? I have rechecked that all xml V3, V4 and V9 passes the validation checks.

**Comment by JonatasViscaino** [comment]
Hi Sebastien, I will close this pull as I will review your new source code and double check everything again

**Pull request closed without merging**
