### PR TITLE
Pain.001.001.03 fix in create_xml_v3 function

### PR DESCRIPTION
**Pull request by JonatasViscaino**
Hi Sebastien,

As promised I reviewed the pain.001.001.03 and did some modifications in order to be more accurate with the schema, please check below what was my changes:
- added datetime library to use for the CreDtTm so this info comes from the program and not from the CSV
- added NbOfTxs calculation so this info comes from the program and it's based in the number of lines in the CSV
- added CtrlSum that was missing and calculate based on the CSV data
- removed line 83 cstmr_cdt_trf_initn_element.append(PmtInf_element) that was duplicated under line 209 and would case double line of payments
- commented out NbofTxs and CtrlSum for each payment as this is optional in the xsd schema and not really needed (I would remove but would prefer that you check as well )
- add CCy element in DbtrAcct that was missing,
- changed location of ChrgBr.
- add InstrId in the payment, this field is optional in the schema but is good to have
- fixed line in CdtrAcct as it was taking creditor_agent_BIC instead of creditor_account_IBAN

Please let me know your comments and if you encounter any problems.

Best Regards,
Jonatas Rodriguez

### CODE REVIEW

**Comment by sebastienrousseau** [comment]
@JonatasViscaino many thanks for doing this!

Let me go through all your changes and check on my side. Just a few comments so far:

 - `datetime`, that is a good call
 - `NbOfTxs`, same here, need to check how this will work with SQLite data
 - `CtrlSum` thanks, need to check how this will work with SQLite data
 
Overall a very good update thank you, I need to run it and promote it to the next release 👍

**Comment by JonatasViscaino** [comment]
Hi Sebastien,

Thank you for your answer.

I fixed the lint issue and I hope now it passes the test.

I see that it got reject on line 234, with the creditor_account_IBAN that I changed. I checked the database and I believe this is the name of the column but maybe I am wrong. Could you please double check this error? Maybe I am missing something.

Regarding your comments for NbOfTxs and CtrlSum, it would not be so difficult to do the same calculations in the SQLite, for the NBOfTxs you would only need to do a query of count and for the CtrlSum would be a query of Sum.

Hopefully everything works now :)

**Comment by sebastienrousseau** [comment]
@JonatasViscaino Can you check at the unit tests as they are failing, not sure if you have updated them with your changes?

**Comment by JonatasViscaino** [comment]
> @JonatasViscaino Can you check at the unit tests as they are failing, not sure if you have updated them with your changes?

I updated the testunit, I hope it works now

**Comment by sebastienrousseau** [comment]
@JonatasViscaino This works now thanks, 

Any chance you could update the version number to 0.0.22 in these files:

- setup.cfg
- setup.py
- pyproject.toml
- TEMPLATE.md
- __init__py

and also update the xmlschema version to 2.3.1

After these changes I will be able to promote your changes and publish a new version.

Let me know if that's ok?

Thanks in advance

**Comment by sebastienrousseau** [comment]
@JonatasViscaino thanks for the changes, just running the jobs and should be able to merge your updates as soon as they have completed. Thanks again for your great help on this 😊

**Pull request merged**
